name: hdf5-tutorial
channels:
  - conda-forge
dependencies:
  - python ==3.10
  - jupyter
  - h5py
  - hdf5
  - hdf5plugin
  - matplotlib
  - notebook
  - pip
  - pip:
    - hsds
    - h5pyd
    - rise
