version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - HS_ENDPOINT=http://localhost:5101
      - HS_USERNAME=vscode
      - HS_PASSWORD=vscode
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the SN container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:sn
  head:
    image: hdfgroup/hsds:master
    restart: on-failure
    mem_limit: 512m
    environment:
      - TARGET_SN_COUNT=1
      - TARGET_DN_COUNT=4
      - NODE_TYPE=head_node
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
    ports:
      - 5100
    volumes:
      - ../hsds/data:/data
      - ../hsds/config/:/config/
  dn1:
    image: hdfgroup/hsds:master
    restart: on-failure
    mem_limit: 1g
    environment:
      - NODE_TYPE=dn
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
    ports:
      - 6101
    depends_on:
      - head
    volumes:
      - ../hsds/data:/data
      - ../hsds/config/:/config/
    links:
      - head
  dn2:
    image: hdfgroup/hsds:master
    restart: on-failure
    mem_limit: 1g
    environment:
      - NODE_TYPE=dn
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
    ports:
      - 6102
    depends_on:
      - head
    volumes:
      - ../hsds/data:/data
      - ../hsds/config/:/config/
    links:
      - head
  dn3:
    image: hdfgroup/hsds:master
    restart: on-failure
    mem_limit: 1g
    environment:
      - NODE_TYPE=dn
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
    ports:
      - 6103
    depends_on:
      - head
    volumes:
      - ../hsds/data:/data
      - ../hsds/config/:/config/
    links:
      - head
  dn4:
    image: hdfgroup/hsds:master
    restart: on-failure
    mem_limit: 1g
    environment:
      - NODE_TYPE=dn
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
    ports:
      - 6104
    depends_on:
      - head
    volumes:
      - ../hsds/data:/data
      - ../hsds/config/:/config/
    links:
      - head
  sn:
    image: hdfgroup/hsds:master
    restart: on-failure
    mem_limit: 1g
    environment:
      - SN_PORT=5101
      - NODE_TYPE=sn
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
      - HSDS_ENDPOINT=http://localhost:5101
    ports:
      - 5101:5101
    depends_on:
      - head
    volumes:
      - ../hsds/data:/data
      - ../hsds/config/:/config/
    links:
      - head
