version: "2"
services:
  head:
    image: hdfgroup/hsds:master
    restart: on-failure
    mem_limit: 512m
    environment:
      - TARGET_SN_COUNT=4
      - TARGET_DN_COUNT=4
      - NODE_TYPE=head_node
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
    ports:
      - 5100
    volumes:
      - /home/codespace/hsds/data:/data
  dn:
    image: hdfgroup/hsds
    restart: on-failure
    mem_limit: 1g
    environment:
      - NODE_TYPE=dn
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
    ports:
      - 6101
    depends_on:
      - head
    volumes:
      - /home/codespace/hsds/data:/data
    links:
      - head
  sn:
    image: hdfgroup/hsds
    restart: on-failure
    mem_limit: 1g
    environment:
      - SN_PORT=510
      - NODE_TYPE=sn
      - ROOT_DIR=/data
      - BUCKET_NAME=hsdstest
      - HSDS_ENDPOINT=http://localhost:5101
    ports:
      - 5101:5101
    depends_on:
      - head
    volumes:
      - /home/codespace/hsds/data:/data
    links:
      - head
